---
branches:
  only:
  - develop

language: node_js

node_js:
  - "4"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphicsmagick

script:
  - npm test
  - npm run coveralls
