environment:
  matrix:
  - nodejs_version: "4"

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - appveyor-retry npm install

# Post-install test scripts.
test_script:
  - bash -lc "/c/projects/entoj-core/scripts/tests"

# Don't actually build.
build: off
